/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('inventory').del();
  
  // Insert seed entries
  await knex('inventory').insert([
    {
      id: 1,
      name: 'Professional Hair Scissors',
      description: 'High-quality stainless steel hair cutting scissors',
      sku: 'SCIS001',
      category: 'Tools',
      brand: 'Jaguar',
      cost_price: 85.00,
      selling_price: 120.00,
      current_stock: 8,
      minimum_stock: 3,
      maximum_stock: 15,
      unit: 'piece',
      supplier: 'Beauty Supply Co.',
      supplier_contact: 'orders@beautysupply.com',
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 2,
      name: 'Premium Shampoo',
      description: 'Professional grade shampoo for all hair types',
      sku: 'SHAM001',
      category: 'Hair Care',
      brand: 'Paul Mitchell',
      cost_price: 12.50,
      selling_price: 18.00,
      current_stock: 25,
      minimum_stock: 10,
      maximum_stock: 50,
      unit: 'bottle',
      supplier: 'Professional Hair Products',
      supplier_contact: '+1234567899',
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 3,
      name: 'Hair Clippers',
      description: 'Professional cordless hair clippers with multiple guards',
      sku: 'CLIP001',
      category: 'Tools',
      brand: 'Wahl',
      cost_price: 65.00,
      selling_price: 95.00,
      current_stock: 6,
      minimum_stock: 2,
      maximum_stock: 10,
      unit: 'piece',
      supplier: 'Barber Equipment Inc.',
      supplier_contact: 'sales@barberequip.com',
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 4,
      name: 'Styling Gel',
      description: 'Strong hold styling gel for modern hairstyles',
      sku: 'GEL001',
      category: 'Styling Products',
      brand: 'American Crew',
      cost_price: 8.25,
      selling_price: 12.00,
      current_stock: 15,
      minimum_stock: 8,
      maximum_stock: 30,
      unit: 'tube',
      supplier: 'Professional Hair Products',
      supplier_contact: '+1234567899',
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 5,
      name: 'Shaving Cream',
      description: 'Rich, luxurious shaving cream for smooth shaves',
      sku: 'CREAM001',
      category: 'Shave Products',
      brand: 'The Art of Shaving',
      cost_price: 15.00,
      selling_price: 22.00,
      current_stock: 12,
      minimum_stock: 6,
      maximum_stock: 25,
      unit: 'tube',
      supplier: 'Gentleman\'s Supply',
      supplier_contact: 'info@gentlemansupply.com',
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 6,
      name: 'Hot Towels',
      description: 'Soft cotton towels for hot towel treatments',
      sku: 'TOW001',
      category: 'Towels & Linens',
      brand: 'Pro Towel',
      cost_price: 3.50,
      selling_price: 5.00,
      current_stock: 45,
      minimum_stock: 20,
      maximum_stock: 60,
      unit: 'piece',
      supplier: 'Linen Supply Co.',
      supplier_contact: '+1234567898',
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 7,
      name: 'Beard Oil',
      description: 'Nourishing beard oil with essential oils',
      sku: 'OIL001',
      category: 'Beard Care',
      brand: 'Honest Amish',
      cost_price: 11.00,
      selling_price: 16.50,
      current_stock: 8,
      minimum_stock: 5,
      maximum_stock: 20,
      unit: 'bottle',
      supplier: 'Beard Care Specialists',
      supplier_contact: 'orders@beardcare.com',
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 8,
      name: 'Razor Blades',
      description: 'Premium stainless steel razor blades',
      sku: 'BLADE001',
      category: 'Shave Products',
      brand: 'Feather',
      cost_price: 0.75,
      selling_price: 1.25,
      current_stock: 120,
      minimum_stock: 50,
      maximum_stock: 200,
      unit: 'piece',
      supplier: 'Shaving Supplies Direct',
      supplier_contact: 'support@shavingsupplies.com',
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 9,
      name: 'Aftershave Balm',
      description: 'Soothing aftershave balm with moisturizing properties',
      sku: 'BALM001',
      category: 'Shave Products',
      brand: 'Nivea Men',
      cost_price: 6.50,
      selling_price: 9.75,
      current_stock: 18,
      minimum_stock: 8,
      maximum_stock: 30,
      unit: 'bottle',
      supplier: 'Professional Hair Products',
      supplier_contact: '+1234567899',
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 10,
      name: 'Disinfectant Spray',
      description: 'Professional grade disinfectant for tools and surfaces',
      sku: 'DIS001',
      category: 'Sanitation',
      brand: 'Barbicide',
      cost_price: 8.00,
      selling_price: 12.50,
      current_stock: 5,
      minimum_stock: 3,
      maximum_stock: 15,
      unit: 'bottle',
      supplier: 'Salon Safety Supply',
      supplier_contact: 'orders@salonsafety.com',
      notes: 'Low stock - reorder soon',
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    }
  ]);
};